services:
  monitor:
    image: kaanmertkoc1/simple-monitor:latest
    container_name: simple-monitor
    expose:
      - "8080"
    volumes:
      - ./data:/data
    restart: unless-stopped
    privileged: true
    networks:
      - monitor-network

  nginx:
    image: nginx:alpine
    container_name: monitor-nginx
    ports:
      - "9090:80"    # Single port, easy to remember
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - monitor-network
    depends_on:
      - monitor

networks:
  monitor-network:
    driver: bridge