version: '3.8'

services:
  monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - monitor-data:/data
    restart: unless-stopped
    privileged: true

volumes:
  monitor-data: